[package]
name = "elcarax_platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = []
native = ["dep:winit", "dep:rfd"]

[dependencies]
rfd = { version = "0.15.4", optional = true, default-features = false, features = ["xdg-portal", "async-std"] }
winit = { version = "0.30.12", optional = true }
